steps:
  - name: node:16.15.0
    entrypoint: yarn
    args: [ "install" ]
  - name: node:16.15.0
    entrypoint: yarn
    args: [ "run", "create-env" ]
    env:
      - 'EMAIL_FROM=${_EMAIL_FROM}'
      - 'EMAIL_USER=${_EMAIL_USER}'
      - 'EMAIL_PASS=${_EMAIL_PASS}'
      - 'DATABASE_URL=${_DATABASE_URL}'
  - name: node:16.15.0
    entrypoint: yarn
    args: [ "build" ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy" ]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY