name: Deploy to Google Cloud
on:
  push:
    branches:
      - 'main'

jobs:
  gcloud:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - id: build
        name: Build dist
        run: |-
          yarn install
          yarn build
      - name: Initialize Google Cloud SDK & Deploy
        uses: etereo-io/deploy-gae-action@master
        with:
          gae_config_path: './app.yaml'
          service_account: ${{ secrets.GCP_SA_KEY_BASE64 }}
          project_id: ${{ secrets.GCP_PROJECT }}
