name: Deploy to Google Cloud
on:
  push:
    branches:
      - 'main'

jobs:
  gcloud:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - id: build
        name: Build dist
        run: |-
          yarn install
          yarn build
      - id: deploy
        name: Deploy to App Engine
        uses: ./
        with:
          version: gcloud
          promote: false
          working_directory: ${{ github.workspace }}

      - name: Clean Up
        if: ${{ always() }}
        run: |-
          gcloud app services delete "${{ github.job }}-${{ github.run_number }}" \
            --quiet \
            --project="${{ secrets.GCP_PROJECT }}"
