on:
  push:
    branches: [ main ]

name: Deploy to PROD

jobs:
  runs-on: ubuntu-latest

  job_id:
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'